DROP TABLE IF EXISTS orders;

CREATE TABLE orders (
    restaurant_id INTEGER,
    restaurant_name TEXT,
    subzone TEXT,
    city TEXT,
    order_id INTEGER PRIMARY KEY,
    order_placed_at TEXT,
    order_status TEXT,
    delivery TEXT,
    distance REAL,
    items_in_order TEXT,
    instructions TEXT,
    discount_construct TEXT,
    bill_subtotal REAL,
    packaging_charges REAL,
    restaurant_discount_promo REAL,
    restaurant_discount_other REAL,
    gold_discount REAL,
    brand_pack_discount REAL,
    total REAL,
    rating REAL,
    review TEXT,
    cancellation_reason TEXT,
    restaurant_compensation REAL, 
    restaurant_penalty REAL,
    kpt_minutes REAL,
    rider_wait_minutes REAL,
    order_ready_marked TEXT,
    customer_complaint_tag TEXT,
    customer_id TEXT,
    distance_under_1km BOOLEAN,
    discount_type TEXT,
    discount_percent REAL,
    discount_cap REAL,
    discount_amount REAL,
    buy_quantity INTEGER,
    get_quantity INTEGER,
    kpt_missing_on_delivered BOOLEAN,
    rider_wait_missing_on_delivered BOOLEAN,
    item_count INTEGER,
    order_date TEXT,
    order_hour INTEGER,
    order_weekday TEXT
);